snapms_site/snapms/urls.py
from django.urls import path
from . import views

app_name = "snapms"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("submit", views.handle_snapms, name="handle_snapms"),
    path("output/<uuid:job_id>", views.job_output, name="job_output"),
    path(
        "output/<uuid:job_id>/<str:fmt>", views.download_output, name="download_output"
    ),
    path("docs", views.docs, name="docs"),
]

snapms_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    template_name = "base.html"


urlpatterns = [
    path("", IndexView.as_view()),
    path("admin/", admin.site.urls),
    path("django-rq/", include("django_rq.urls")),
    path("snapms/", include("snapms_site.snapms.urls")),
]

snapms_site/snapms/models.py
import uuid
from enum import Enum
from django.db import models


class FileFormat(str, Enum):
    graphml = "graphml"
    cytoscape = "cytoscape"


class Status(str, Enum):
    queued = "queued"
    running = "running"
    failed = "failed"
    completed = "completed"


class Job(models.Model):
    """Model for tracking SnapMS Jobs.
    Automatically creates a UUID and sets status to queued when created.

    Tracks date created, archived (for when over expiry date: probably 6 months),
    status, inputfile name, and parameters used.
    """

    id = models.CharField(
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        editable=False,
        max_length=32,
    )
    created = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    status = models.CharField(max_length=128, default=Status.queued.value)
    inputfile = models.CharField(max_length=256)
    parameters = models.TextField()

snapms_site/snapms/views.py
import csv
import json
from pathlib import Path
from typing import Dict, Optional
from uuid import UUID

from django.conf import settings
from django.core.serializers import serialize
from django.http import HttpRequest, HttpResponse, JsonResponse, FileResponse
from django.http.response import (
    HttpResponseBadRequest,
    HttpResponseNotAllowed,
    HttpResponseNotFound,
)
from django.shortcuts import render
from django.utils.datastructures import MultiValueDictKeyError

from snapms.config import AtlasFilter, Parameters

from .models import Job, FileFormat
from .tasks import run_snapms_gnps, run_snapms_masslist


def docs(request: HttpRequest) -> HttpResponse:
    """View for docs page"""
    context = dict(page_name="SnapMS Documentation")
    return render(request, "docs.html", context)


def dashboard(request: HttpRequest) -> HttpResponse:
    """View for dashboard page"""
    context = dict(page_name="SnapMS")
    return render(request, "dashboard.html", context)


def handle_snapms(request: HttpRequest) -> HttpResponse:
    """Handle post of SnapMS passing to handler function"""
    if request.method == "POST":
        return handle_snapms_request(request)
    return HttpResponseNotAllowed(["POST"])


def job_output(request: HttpRequest, job_id: UUID) -> HttpResponse:
    """Handle access of Job output and status in HTML form"""
    job_data = get_job_data(job_id)
    context = dict(job=job_data, job_id=job_id)
    if "application/json" in request.META["HTTP_ACCEPT"]:
        return JsonResponse(context)
    return render(request, "output.html", context)


def download_output(request: HttpRequest, job_id: UUID, fmt: str) -> HttpResponse:
    """Handle sending output file"""
    if request.method != "GET":
        return HttpResponseNotAllowed(["GET"])
    try:
        fmt = FileFormat(fmt)
        if get_job_data(job_id) is None:
            return HttpResponseNotFound("Job does not exist")
        return send_job_output(job_id, fmt)
    except ValueError:
        return HttpResponseBadRequest("File format is not available")


### Helper functions
def send_job_output(job_id: UUID, fmt: FileFormat) -> HttpResponse:
    job_dir = Path(settings.SNAPMS_DATADIR) / str(job_id)
    if fmt == FileFormat.cytoscape:
        output_file = job_dir / "snapms.cys"
    elif fmt == FileFormat.graphml:
        output_file = find_graphml_output(job_dir)
    fname = f"snapms_{job_id}{output_file.suffix}"
    return FileResponse(output_file.open("rb"), filename=fname)


def find_graphml_output(job_dir: Path) -> Path:
    for ftype in (".zip", ".graphml"):
        flist = list(job_dir.glob(f"*{ftype}"))
        if flist:
            return flist[0]


def get_job_data(job_id: UUID) -> Optional[Dict]:
    try:
        job = Job.objects.get(id=str(job_id))
        return serialize("python", [job])[0]
    except Job.DoesNotExist:
        return None


def handle_snapms_request(request: HttpRequest) -> HttpResponse:
    """Method for handling work of creating a new job and passing to worker queue"""
    # from collections import defaultdict

    # data = defaultdict(str)
    data = json.loads(request.POST["metadata"])
    print(data)
    # Try to get the file
    try:
        upload_file = request.FILES["file"]
    except MultiValueDictKeyError:
        upload_file = None
    # Create Job
    job = Job.objects.create(
        inputfile=upload_file or "masslist.csv",
        parameters=json.dumps(data),
    )
    job_id = str(job.id)
    # Setup job directory
    job_dir = Path(settings.SNAPMS_DATADIR) / job_id
    job_dir.mkdir()
    # If no upload_file, convert masslist to csv file
    # If upload_file, save to jobdir
    if upload_file is not None:
        input_file = job_dir.joinpath(upload_file.name)
        with input_file.open("wb") as f:
            for chunk in upload_file.chunks():
                f.write(chunk)
    else:
        input_file = save_convert_masslist(data["masslist"], job_dir)

    if data["reference_db"] == "coconut":
        db_path = settings.COCONUT_FILE
    else:
        db_path = settings.NPATLAS_FILE

    parameters = Parameters(
        file_path=input_file,
        atlas_db_path=db_path,
        output_path=job_dir,
        ppm_error=int(data["ppm_error"]),
        adduct_list=data["adduct_list"],
        remove_duplicates=data["remove_duplicates"],
        min_gnps_size=int(data["min_gnps_size"]),
        max_gnps_size=int(data["max_gnps_size"]),
        min_atlas_size=int(data["min_atlas_size"]),
        min_group_size=int(data["min_group_size"]),
        max_edge_count=int(data["max_edge_count"]),
        max_node_count=int(data["max_node_count"]),
        job_id=job_id,
        atlas_filter=AtlasFilter(data["reference_db"]),
        custom_filter=data["custom_value"],
    )
    if parameters.file_type == "csv":
        run_snapms_masslist.delay(parameters, job_id)
    elif parameters.file_type == "graphml":
        parameters.compress_output = True
        run_snapms_gnps.delay(parameters, job_id)
    elif parameters.file_type == "cys":
        return HttpResponseBadRequest("Cytoscape import is not yet supported")
    else:
        return HttpResponseBadRequest("Input file format not supported")
    return HttpResponse(json.dumps(dict(success=True, job_id=job_id)))


def save_convert_masslist(masslist: str, job_dir: Path) -> Path:
    """Take a masslist for the front end and convert to a CSV file, returning the Path"""
    mfile = job_dir / "mass_list.csv"
    with mfile.open("w") as f:
        csvwriter = csv.writer(f)
        csvwriter.writerow(["m/z"])
        csvwriter.writerows([[float(x)] for x in masslist.split("\n") if x])
    return mfile

snapms_site/snapms/templates/docs.html
{% extends 'simple_template.html' %}

{% block page_content %}
Docs to come!
{% endblock %}

snapms_site/snapms/templates/output.html
{% extends 'simple_template.html' %}

{% block page_content %}
{{ job|json_script:"snapms_job" }}
{{ job_id|json_script:"snapms_job_id" }}
<div class="container-fluid border mb-4 py-2">
    <b>Bookmark this page to find your results later.</b>
</div>
<div class="container-fluid" id="vue-app">
    <div class="row" v-if="job === null">
        <h5 class="error">ERROR: Job {{ job_id }} could not be found</h5>
    </div>
    <div class="row" v-else>
        <div class="col-12">
            <h5><b>Job</b> - [[ job_id ]]</h5>
            <h5><b>Status</b> - <span :class="jobStatus">[[ job.fields.status ]]</span></h5>
            <i v-if="!jobDone">The website will automatically check and update the job status every 15 seconds.</i>
        </div>
        <div class="col-12 py-2">
            <p><b>Submitted</b> - [[ job.fields.created ]]</p>
            <p><b>Input</b> - [[ job.fields.inputfile ]]</p>
            <!-- <p><b>Parameters</b> - [[ job.fields.parameters ]]</p> -->
        </div>
        <div class="col-12 pt-4" v-if="job.fields.status === 'completed'">
            <!-- If job was submitted with a masslist input -->
            <a class="btn btn-prim-solid" :href="`/snapms/output/${job_id}/graphml`"
                :download="`snapms_${job_id}.graphml`" v-if="this.job.fields.inputfile.endsWith('csv')">
                Download graphML file
            </a>
            <!-- If job was submitted with a network input -->
            <a class="btn btn-prim-solid" :href="`/snapms/output/${job_id}/graphml`" :download="`snapms_${job_id}.zip`"
                v-else>
                Download zipped graphML files
            </a>
            <a class="btn btn-prim-solid" :href="`/snapms/output/${job_id}/cytoscape`"
                :download="`snapms_${job_id}.cys`">
                Download Cytoscape file
            </a>
        </div>
    </div>
</div>
<script>
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    var app = new Vue({
        delimiters: ["[[", "]]"],
        el: '#vue-app',
        data: {
            job_id: null,
            job: {},
        },
        computed: {
            jobDone: function () {
                if (this.job == null) return true
                if (this.job.fields.status === "running" || this.job.fields.status === "queued") return false
                return true
            },
            jobStatus: function () {
                if (this.job == null) return "text-danger"
                if (!this.jobDone) return "text-warning"
                return "text-success"
            }
        },
        created() {
            this.fetchData()
        },
        methods: {
            fetchData: function () {
                this.job = JSON.parse(document.getElementById('snapms_job').textContent)
                this.job_id = JSON.parse(document.getElementById('snapms_job_id').textContent)
                if (!this.jobDone) {
                    this.watchJob()
                }
            },
            watchJob: async function () {
                const result = await axios.get(`/snapms/output/${this.job_id}`);
                this.job = result.data.job
                await sleep(15000)
                if (!this.jobDone) {
                    this.watchJob()
                }
            },
        }
    })
</script>
{% endblock %}

snapms_site/snapms/templates/simple_template.html
{% extends "base.html" %}

{% block title %}Natural Products Atlas | {{ page_name }}{% endblock %}

{% block content %}
<style>
    h4 {
        text-transform: uppercase;
        font-weight: 700;
    }
</style>

<div class="container bg-light p-4">
    <div class="container-fluid mt-3 bg-white rounded py-3">
        <h4>{{ page_name }}</h4>
        {%block page_content%}
        {% endblock %}
    </div>
</div>

{% endblock %}

snapms_site/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS-->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- jQuery + Bootstrap + Popper JS-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- VueJS for reactivity -->
    <!-- development version, includes helpful console warnings -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <!-- production version, optimized for size and speed -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/vue@2"></script> -->
    <!-- Axios for easy AJAX -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"
        integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ=="
        crossorigin="anonymous"></script>

    <!-- Static resources -->
    {% load static %}
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- For dev -->
    <script src="{% static 'js/typeahead.bundle.js' %}"></script>
    <!-- For prod -->
    <!-- <script src="{% static 'js/typeahead.bundle.min.js' %}"></script> -->
    <title>{% block title %}Natural Products Atlas{% endblock %}</title>
    <script>
        function showLoader() {
            $("#loader-div").removeClass("d-none")
        }
    </script>
</head>

<body>
    <a name="top"></a>
    <div id="loader-div" class="d-none container-fluid text-center justify-content-center">
        <div class="row">
            <div class="loader">Loading...</div>
            <h2 class="text-white">Loading...</h2>
        </div>
    </div>
    <div class="container py-4">
        <div class="row">
            <div class="col-lg-2 d-flex justify-content-center">
                <a href="#" id="site-logo">
                    <img src="{% static 'img/npatlas_logo_square_small.png' %}" alt="logo" />
                </a>
            </div>
            <div class="col-lg-8 text-center">
                <a href="#" id="site-title">
                    <span class="logo-text">The Natural Products Atlas</span>
                    <!-- <span class="logo-subtext">Network views of chemical space</span> -->
                </a>
            </div>

        </div>
    </div>
    <div class="container">
        <div class="row align-items-center">
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="main_nav">
                        <ul class="navbar-nav">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'snapms:dashboard' %}">Snap MS</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'rq_home' %}">Django RQ</a>
                            </li>
                        </ul>
                    </div>
            </nav>
        </div>
    </div>

    <div id="content" class="pb-3">
        {% block content %}{% endblock %}
    </div>

    <div class="container">
        <hr>
    </div>

</body>

</html>